name: build

on: [push, pull_request, workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build

      - name: Upload Jars
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Sherds API
          if-no-files-found: error
          path: |
            fabric/build/libs
            neoforge/build/libs
            common/build/libs